config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "events#index"

  resources :events, only: [:index] do
    resources :awards
  end

  namespace :admin do
    root to: 'events#index'
    resources :events
    resources :teams do
      resources :memberships
    end
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :team

  delegate :name, to: :user

  validates :user_id, uniqueness: { scope: :team_id }
end

app/controllers/admin/memberships_controller.rb
class Admin::MembershipsController < Admin::BaseController
  before_filter :load_team
  before_filter :load_membership, only: [:edit, :update, :destroy]

  def index
    @memberships = @team.memberships
  end

  def new
    @membership = Membership.new
    load_users
  end

  def create
    @membership = @team.memberships.build(membership)
    if @membership.save
      redirect_to admin_team_memberships_path(@team), notice: 'The team member was created succesfully'
    else
      load_users
      render action: :new
    end
  end

  def destroy
    name = @membership.name
    @membership.destroy
    redirect_to admin_team_memberships_path(@team), notice: "#{name} was removed from the team succesfully"
  end

  private
  def load_team
    @team = Team.find(params[:team_id])
  end

  def membership
    params.require(:membership).permit(:user_id)
  end

  def load_membership
    @membership = @team.memberships.find(params[:id])
  end

  def load_users
    @users  = User.order(:name) - @team.users
  end
end

app/views/admin/memberships/_form.html.haml
= f.bootstrap_collection_select :user_id, @users, :id, :name
= f.submit class: "btn btn-primary"
= link_to "Cancel", admin_team_memberships_path(@team), class: "btn"

app/views/admin/memberships/_membership.html.haml
%tr
  %td= membership.name
  %td= link_to 'Delete', admin_team_membership_path(membership.team, membership), method: :delete, data: { confirm: "Are you sure?" }

app/views/admin/memberships/index.html.haml
.page-header
  %h1
    = @team.name
    %small Team Members

  = link_to 'New Member', new_admin_team_membership_path(@team), class: "btn btn-primary"

%table.table.striped#members
  %tbody= render @memberships

app/views/admin/memberships/new.html.haml
.page-header
  %h1
    New Team Member
    %small for #{@team.name}

= form_for [:admin, @team, @membership] do |f|
  = render 'form', { f: f }