config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "events#index"

  resources :events, only: [:index] do
    resources :awards
  end

  namespace :admin do
    root to: 'events#index'
    resources :events
    resources :teams do
      resources :memberships
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  belongs_to :team

  has_many :awards

  validates :opens_at, presence: true

  delegate :name, to: :team, prefix: true
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  before_filter :load_event, only: [:edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
    @teams = Team.all
  end

  def create
    @event         = Event.new(event)
    @event.creator = current_user

    if @event.save
      redirect_to admin_events_path, notice: "Event created succesfully"
    else
      @teams = Team.all
      render action: :new
    end
  end

  def edit
    @teams = Team.all
  end

  def update
    if @event.update_attributes(event)
      redirect_to admin_events_path, notice: "Event updated succesfully"
    else
      @teams = Team.all
      render action: :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to admin_events_path
  end

  private
  def event
    params.require(:event).permit(:name, :opens_at, :team_id)
  end

  def load_event
    @event = Event.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = current_user.events
  end
end

app/views/admin/events/_event.html.haml
%tr
  %td= event.name
  %td= event.team_name
  %td= link_to 'Edit', edit_admin_event_path(event)
  %td= link_to 'Delete', admin_event_path(event), method: :delete

app/views/admin/events/_form.html.haml
= f.bootstrap_text_field :name
= f.bootstrap_collection_select :team_id, @teams, :id, :name
.form-group
  = f.label :opens_at
  = f.datetime_select :opens_at
= f.submit class: 'btn btn-primary'
= link_to "Cancel", admin_events_path, class: "btn"

app/views/admin/events/edit.html.haml
%h1 Edit Event

= form_for [:admin, @event] do |f|
  = render 'form', { f: f }

app/views/admin/events/index.html.haml
.page-header
  %h1 Events

  = link_to 'Create Event', new_admin_event_path, class: "btn btn-primary"

%table.table.table-striped
  %tbody= render @events

app/views/admin/events/new.html.haml
%h1 New Event

.row
  .col-md-6
    = form_for [:admin, @event] do |f|
      = render 'form', { f: f }