config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "events#index"

  resources :events, only: [:index] do
    resources :awards
  end

  namespace :admin do
    root to: 'events#index'
    resources :events
    resources :teams do
      resources :memberships
    end
  end
end

app/models/award.rb
class Award < ActiveRecord::Base
  belongs_to :user
  belongs_to :receiver, class_name: "User"
  belongs_to :event

  delegate :name, to: :receiver, prefix: true

  validates :user, presence: true
  validates :points, numericality: true
  validates_with AwardValidator
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  before_filter :load_event

  def index
    @awards = current_user.awards.where(event_id: @event.id)
  end

  def new
    @award = Award.new
    load_users
  end

  def create
    @award      = @event.awards.build(award)
    @award.user = current_user
    if @award.save
      redirect_to event_awards_path(@event)
    else
      load_users
      render action: :new
    end
  end

  def edit
    @award = current_user.awards.find(params[:id])
    @users = User.where.not(id: current_user.id).order(:name)
  end

  def update
    @award = current_user.awards.find(params[:id])
    if @award.update_attributes(award)
      redirect_to event_awards_path(@event)
    else
      load_users
      render action: :edit
    end
  end

  def destroy
    @award = current_user.awards.find(params[:id])
    @award.destroy
    redirect_to event_awards_path(@event)
  end

  private
  def award
    params.require(:award).permit(:receiver_id, :points, :comment)
  end

  def load_event
    @event = current_user.events.find(params[:event_id])
  end

  def load_users
    @team = @event.team
    @users = @team.users.where.not(id: current_user.id).order(:name)
  end
end

app/views/awards/_award.html.haml
%tr
  %td= award.receiver_name
  %td= award.points
  %td= link_to 'Edit', edit_event_award_path(@event, award)
  %td= link_to 'Delete', event_award_path(@event, award), method: :delete, data: { confirm: "Are you sure?" }

app/views/awards/_form.html.haml
= f.bootstrap_collection_select :receiver_id, @users, :id, :name
= f.bootstrap_text_field :points
= f.bootstrap_text_area :comment
= f.submit class: "btn btn-primary"
= link_to "Cancel", event_awards_path(@event), class: "btn"

app/views/awards/edit.html.haml
%h1 Edit Award

= form_for [ @event, @award ] do |f|
  = render 'form', { f: f }

app/views/awards/index.html.haml
.page-header
  %h1
    = @event.name
    %small Award

  = link_to 'Award', new_event_award_path, class: "btn btn-primary"

%table.table.table-striped
  %tbody= render @awards

app/views/awards/new.html.haml
%h1 New Award

= form_for [@event, @award] do |f|
  = render 'form', { f: f }