config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "events#index"

  resources :events, only: [:index] do
    resources :awards
  end

  namespace :admin do
    root to: 'events#index'
    resources :events
    resources :teams do
      resources :memberships
    end
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships
  has_many :events
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < Admin::BaseController
  before_filter :load_team, only: [:edit, :update, :destroy]

  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team)
    if @team.save
      redirect_to admin_teams_path, notice: 'The team was created succesfully'
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @team.update_attributes(team)
      redirect_to admin_teams_path, notice: 'The team was updated succesfully'
    else
      render action: 'edit'
    end
  end

  def destroy
    @team.destroy
    redirect_to admin_teams_path, notice: 'The team was deleted succesfully'
  end

  private
  def team
    params.require(:team).permit(:name)
  end

  def load_team
    @team = Team.find(params[:id])
  end
end

app/views/admin/teams/_form.html.haml
= f.bootstrap_text_field :name
= f.submit class: "btn btn-primary"
= link_to "Cancel", admin_teams_path, class: "btn"

app/views/admin/teams/_team.html.haml
%tr
  %td= team.name
  %td= link_to 'Members', admin_team_memberships_path(team)
  %td= link_to 'Edit', edit_admin_team_path(team)
  %td= link_to 'Delete', admin_team_path(team), method: :delete, data: { confirm: "Are you sure?" }

app/views/admin/teams/edit.html.haml
%h1 Edit Team

= form_for [:admin, @team] do |f|
  = render 'form', { f: f }

app/views/admin/teams/index.html.haml
.page-header
  %h1 Teams

  = link_to 'Create Team', new_admin_team_path, class: "btn btn-primary"

%table.table.table-striped
  %tbody= render @teams

app/views/admin/teams/new.html.haml
%h1 New Team

= form_for [:admin, @team] do |f|
  = render 'form', { f: f }